### ISSUE TITLE
Extra comment in PR

### ISSUE THREAD

**Issue by vankop** [coverallsapp/github-action#5] opened 2019-09-23 13:33 UTC
Hi All!

We faced with problem that `coveralls` produce extra comment in PRs (comments option is disabled via settings). Looks like it works in such way right after we moved to github actions. It will be great, if you can give more info about `action` behaviour.

[Example PR](https://github.com/stylelint/stylelint/pull/4294)

**Comment by XhmikosR** [comment] 2019-09-28 07:00
One would expect the comment to be controlled via the coveralls settings. I haven't tried the action yet, but this is something I always turn off myself.

**Comment by hudochenkov** [comment] 2019-10-01 19:29
We have it disabled:

<img width="621" alt="Screenshot 2019-10-01 at 21 28 45" src="https://user-images.githubusercontent.com/654597/65993913-79b87280-e492-11e9-9fb4-1eb9111dc495.png">

**Comment by XhmikosR** [comment] 2019-10-01 21:47
I actually couldn't reproduce this. It seems it respects the option set in coveralls for me.

**Comment by XhmikosR** [comment] 2019-10-06 11:02
Alright, I just hit this [here](https://github.com/validator/grunt-html/pull/139#issuecomment-538735236). I definitely have comments disabled on the Coveralls project. This is quite annoying if it keeps happening and one has explicitly disabled comments.

@nickmerwin can you please have a look?

**Comment by vankop** [comment] 2019-10-06 11:07
@XhmikosR @nickmerwin start point of investigation could be that comment is authored by `github-action` user not`coveralls` (if you use `coveralls` with other CI you will get comment authored by `coveralls` bot). Maybe this info could help.

**Comment by XhmikosR** [comment] 2019-10-06 11:08
Yeah, I noticed that too. Actions must have another API for this which currently isn't got into consideration or something.

**Comment by XhmikosR** [comment] 2019-10-08 11:53
Not sure who else to ping @nickmerwin @mscoutermarsh @coveralls

**Comment by nickmerwin** [comment] 2019-11-13 19:13
Hi all, apologies for the delay, this is fixed now. 

We originally had repos created by an incoming GitHub Action push with `GITHUB_TOKEN` override the PR comment setting. This is updated to default that setting to true for these newly created repos, so that it can be toggled off as needed after the fact, and GH Action pushes on existing repos will respect the setting.

Thanks.

**Closed by nickmerwin** 2019-11-13 19:13 UTC
