### ISSUE TITLE
Multiple Coverage files not being merged when uploaded

### ISSUE THREAD

**Issue by StuartFerguson** [coverallsapp/github-action#18] opened 2019-10-31 13:50 UTC
In my Github actions workflow I am running 3 dotnet test commands as follows

`  dotnet test "TestsProject1.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov1.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"

  dotnet test "TestsProject2.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov2.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"

  dotnet test "TestsProject3.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov3.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"`

Each of the steps generates its own coverage file.

In my work flow I have a step to upload each of the coverage files as follows (where N in the file name relating to the test step):  

- name: Upload Code Coverage 
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: lcovN.info   

I then have a coverall finished step as follows:

- name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

However what appears to be happening is the 3 files are being uploaded as 3 seperate jobs but the coverage is not being aggregated (i.e. the results I see are from the lcov3.info file).

Is there a way that the files can be uploaded in a single job or is there a way to get the results aggregated?

**Comment by jlabeit** [comment] 2020-01-20 11:33
Hey,
I am having the same issue. I am using a matrix to run multiple tests suites and the notify coveralls with `parallel-finished: true`:
```yml
 checks:
    needs: [checks-modules]
    strategy:
      matrix:
        service:
        - Service/a
        - Service/b
        - Service/c
    runs-on: ubuntu-latest
    steps:
    - name: Test
     run: run test in ${{ matrix.service }}
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        path-to-lcov: ./${{ matrix.service }}/coverage/lcov.info

coveralls-finished:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
```

In coveralls the coverage from all the different jobs show up but the coverage is not aggregated.

**Comment by jlabeit** [comment] 2020-01-20 12:04
On another note this looks like a duplicate of #13

**Comment by jbaris** [comment] 2020-03-05 16:51
> Hey,
> I am having the same issue. I am using a matrix to run multiple tests suites and the notify coveralls with `parallel-finished: true`:
> 
> ```yaml
>  checks:
>     needs: [checks-modules]
>     strategy:
>       matrix:
>         service:
>         - Service/a
>         - Service/b
>         - Service/c
>     runs-on: ubuntu-latest
>     steps:
>     - name: Test
>      run: run test in ${{ matrix.service }}
>     - name: Coveralls
>       uses: coverallsapp/github-action@master
>       with:
>         github-token: ${{ secrets.GITHUB_TOKEN }}
>         parallel: true
>         path-to-lcov: ./${{ matrix.service }}/coverage/lcov.info
> 
> coveralls-finished:
>     needs: [checks]
>     runs-on: ubuntu-latest
>     steps:
>     - name: Coveralls
>       uses: coverallsapp/github-action@master
>       with:
>         github-token: ${{ secrets.GITHUB_TOKEN }}
>         parallel-finished: true
> ```
> 
> In coveralls the coverage from all the different jobs show up but the coverage is not aggregated.

@jlabeit is this code working for you?
I give up, and I start using lcov. But I figure out that jobs does not share the workspace and you need to do that sharing explicity (by using upload/download actions).
Check this out https://github.com/jbaris/todoz-mern-jwt/blob/master/.github/workflows/coverage.yml

**Comment by nickmerwin** [comment] 2020-04-21 22:56
Hi all, we've just released a new version with better parallel support and updated the example configuration in the README:

https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example

**Closed by nickmerwin** 2020-04-21 22:56 UTC
