### ISSUE TITLE
PR comments are not being added

### ISSUE THREAD

**Issue by merlinnot** [coverallsapp/github-action#19] opened 2019-11-01 23:08 UTC
PR comments are not added to pull requests at all. I double checked the configuration, but it seems fine. I also tried multiple options (compact/detailed view etc.). Here's a screenshot:

![67884744-a1106700-fb46-11e9-941a-aefc773af98b](https://user-images.githubusercontent.com/10390061/68061341-a4e9e800-fd04-11e9-83cf-7539517b3a0e.png)

I looked through the source code, but what I've seen so far is that the token is sent to the backend and that's what probably is being used to add a comment, so it looks like there's not much I can fix myself.

**Comment by Dunning-Kruger** [comment] 2019-11-12 15:34
Might be a duplicate of #7

**Comment by merlinnot** [comment] 2019-11-12 16:00
It's not from forked repos, that's why I decided to open a new issue. Is Coveralls even maintained? I also dropped them an email, but no response.

**Comment by nickmerwin** [comment] 2019-11-12 18:43
Hi @merlinnot, could you link me to the repo in question?

**Comment by merlinnot** [comment] 2019-11-12 18:45
Sure! It's not public tho, but I guess you can see some logs on your side?

https://coveralls.io/github/ridedott/rider-service

**Comment by nickmerwin** [comment] 2019-11-12 19:26
@merlinnot thanks, it appears the base build for the latest PR (#108) isn't present on Coveralls:

> 56e8fb1c38142159d4609e44f4b563eba5046c95

This prevents the PR comment from being sent (it needs to know what build to compare it to).

Can you confirm?

**Comment by merlinnot** [comment] 2019-11-12 19:33
Yes, that is correct. That's because GitHub Actions can't trigger other GitHub Actions (we have an Action that merges PRs and then checks don't run on master). I'll fix it straight away and report back!

**Comment by merlinnot** [comment] 2019-11-12 20:11
Ok, I have an example in an open-source repo: https://github.com/ridedott/dependabot-auto-merge-action/pull/91

I checked and the master branch was successfully built, I then updated the PR, it was also successfully built, but no comment was added.

**Comment by nickmerwin** [comment] 2019-11-12 20:27
@merlinnot ok, the workflow that invokes the Coveralls action needs to run on pulls also:

https://github.com/ridedott/dependabot-auto-merge-action/blob/master/.github/workflows/continuous-integration.yaml

```yaml
on: ["push","pull_request"]
```

**Comment by merlinnot** [comment] 2019-11-12 20:40
Yay, it worked! I think it might be a good idea to make a PR with a slight change to this configuration and elaborate a bit on why is this needed. I'd gladly make a PR if you think it's a good idea. Thoughts?

This is the config I tried now and it works:
```yaml
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
```

I didn't want to use `on: ["push","pull_request"]` as it was triggering two separate workflows on every commit I made.

**Comment by merlinnot** [comment] 2019-11-12 20:40
The config means "on every push to the master branch and on every pull request against the master branch".

**Comment by LeMorrow** [comment] 2019-11-14 18:49
Hello, I'm using the `on: [push, pull_request]` but will not get a comment on my PR's the majority of the time. I can see both of these pull requests on coveralls.io, Here are 2 examples where the same yml file gives me different outcomes:

## Example 1 (got comment)
[Pull request](https://github.com/LeMorrow/APOD.Net/pull/8)
[build.yml](https://github.com/LeMorrow/APOD.Net/blob/52cf0b2c2e78362b795507e8c36552edb6ca2952/.github/workflows/build.yml)
Checks
![checks](https://user-images.githubusercontent.com/35617441/68886260-2e42e680-0717-11ea-97b5-e66a089653af.png)


## Example 2 (did not get comment, waited 5h+)
[Pull request](https://github.com/LeMorrow/APOD.Net/pull/17)
[build.yml](https://github.com/LeMorrow/APOD.Net/blob/734e45fa902f1101762fd052c54f3416ed36469e/.github/workflows/build.yml)
Checks
![image](https://user-images.githubusercontent.com/35617441/68886501-9f829980-0717-11ea-93db-dada7a74dc08.png)

**Comment by merlinnot** [comment] 2019-12-07 18:29
Unfortunately I need to reopen this one. It seems to work only for public repositories. The very same, copy-pasted configuration doesn't work for private ones.

**Comment by mad-it** [comment] 2020-04-20 10:17
@nickmerwin Do you have any pointers that could help with commenting on private repositories?

**Comment by nickmerwin** [comment] 2020-04-21 23:20
Hi @mad-it and @merlinnot you'll need to add our bot @coveralls as a collaborator to the private repo to receive PR comments.

**Closed by nickmerwin** 2020-04-21 23:20 UTC

**Comment by afinetooth** [comment] 2020-05-24 19:06
An update for anyone still experiencing this issue:

The [coveralls bot](https://github.com/coveralls) now automatically accepts invitations every 5 min, so if you're not receiving PR comments within 10-15 minutes, send an email to support@coveralls.io and someone will try to resolve the issue.

In order to receive PR comments, the [coveralls bot](https://github.com/coveralls) needs `write` permission on your repo. (`read-only` permission, available through GH orgs, won't work.)

The traditional manner of adding collaborators to your (private) repo applies, so here's how to invite the [coveralls bot](https://github.com/coveralls):

### How to add the [coveralls bot](https://github.com/coveralls) to your repo:

1. On your repo, go to **Settings > Manage Access**.
2. Click **Invite a collaborator**.
3. Enter `coveralls`
4. Click **Add coveralls to [your-repo]**.
5. Coveralls will auto-accept your invitation within 5-10 min.*

_* Coveralls checks for new invitations every 5 min. If your invitation hasn't been accepted within 10-15 min, shoot us an email at support@coveralls.io and we'll accept manually._

**Comment by boredland** [comment] 2021-04-27 17:10
It took me ages to understand this. Even read the docs entry but didn't really understand this is about having the pr-comments.
